INPUT:
  NAME: testlog
  TYPE: file
  PATH: ./logs

FILTER:
  MODE: OR
  FILTERS:
    - TYPE: grep
      OPTIONS:
        IGNORE_CASE: true
        PATTERN: "ERROR"
    - TYPE: grep
      OPTIONS:
        IGNORE_CASE: true
        PATTERN: "WARN"

OUTPUT:
  TYPE: stdout
