INPUT:
  TAG: testlog
  TYPE: file
  PATH: ./json_logs/
  PARSER: json

FILTER:
  MODE: OR
  FILTERS:
    - TYPE: json_grep
      OPTIONS:
        FIELD: "level"
        IGNORE_CASE: true
        PATTERN: "error"

OUTPUT:
  TYPE: stdout
